This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercises for those who teach.

If you find an error or think you've a better way to solve some of them, feel free to open an issue at https://github.com/rougier/numpy-100. File automatically generated. See the documentation to update questions/answers/hints programmatically.

1. Import the numpy package under the name np (★☆☆)
hint: import … as

2. Create a null vector of size 10 (★☆☆)
hint: np.zeros

3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)
hint: array[4]

4. Create a vector with values ranging from 10 to 49 (★☆☆)
hint: arange

5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
hint: reshape

6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
hint: np.nonzero

7. Create a 3x3 identity matrix (★☆☆)
hint: np.eye

8. Create a 3x3x3 array with random values (★☆☆)
hint: np.random.random

9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
hint: min, max

10. Create a random vector of size 30 and find the mean value (★☆☆)
hint: mean

11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
hint: np.diag

12. Normalize a 5x5 random matrix (★☆☆)
hint: (x -mean)/std

13. How to find common values between two arrays? (★☆☆)
hint: np.intersect1d

14. Create a random vector of size 10 and sort it (★★☆)
hint: sort

15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
hint: argmax

16. Subtract the mean of each row of a matrix (★★☆)
hint: mean(axis=,keepdims=)

17. How to get the n largest values of an array (★★★)
Z = np.arange(10000) np.random.shuffle(Z) n = 5 hint: np.argsort | np.argpartition

18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example: 6 --> 36)
hint: np.where

In [1]:
#1
import numpy as np

In [2]:
#2
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
#3
array = np.zeros(10)
array[4] = 1
print(array)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [10]:
#4
print(np.arange(10,50,1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [8]:
#5
print(np.arange(0,9).reshape(3,3))

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
#6
x = [1,2,0,0,4,0]
print(np.nonzero(x))

(array([0, 1, 4]),)


In [14]:
#7
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [15]:
#8
print(np.random.random((3,3,3)))

[[[0.64674852 0.79467525 0.26536614]
  [0.95864893 0.57494549 0.11789168]
  [0.30784184 0.54081671 0.7185054 ]]

 [[0.21409697 0.17034206 0.93747283]
  [0.81893663 0.66351758 0.37367365]
  [0.47779255 0.8201928  0.8282764 ]]

 [[0.10069977 0.41975308 0.48887575]
  [0.05760507 0.93948769 0.700647  ]
  [0.58384217 0.83823144 0.34893583]]]


In [16]:
#9
np.random.seed(123)
a = np.random.random((10,10))
a

array([[0.69646919, 0.28613933, 0.22685145, 0.55131477, 0.71946897,
        0.42310646, 0.9807642 , 0.68482974, 0.4809319 , 0.39211752],
       [0.34317802, 0.72904971, 0.43857224, 0.0596779 , 0.39804426,
        0.73799541, 0.18249173, 0.17545176, 0.53155137, 0.53182759],
       [0.63440096, 0.84943179, 0.72445532, 0.61102351, 0.72244338,
        0.32295891, 0.36178866, 0.22826323, 0.29371405, 0.63097612],
       [0.09210494, 0.43370117, 0.43086276, 0.4936851 , 0.42583029,
        0.31226122, 0.42635131, 0.89338916, 0.94416002, 0.50183668],
       [0.62395295, 0.1156184 , 0.31728548, 0.41482621, 0.86630916,
        0.25045537, 0.48303426, 0.98555979, 0.51948512, 0.61289453],
       [0.12062867, 0.8263408 , 0.60306013, 0.54506801, 0.34276383,
        0.30412079, 0.41702221, 0.68130077, 0.87545684, 0.51042234],
       [0.66931378, 0.58593655, 0.6249035 , 0.67468905, 0.84234244,
        0.08319499, 0.76368284, 0.24366637, 0.19422296, 0.57245696],
       [0.09571252, 0.88532683, 0.6272489

In [20]:
print(np.min(a))
print(np.max(a))

0.01612920669501683
0.9953584820340174


In [22]:
#10
np.random.seed(123)
a = np.random.random(30)
np.mean(a)

0.4983096481504978

In [23]:
#11
x = np.diag(np.arange(5),k=-1)
print(x)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 1 0 0 0 0]
 [0 0 2 0 0 0]
 [0 0 0 3 0 0]
 [0 0 0 0 4 0]]


In [24]:
#12 Normalize a 5x5 random matrix
x = np.random.normal(0, 1, (5, 5))
print(x)

[[-0.14006872 -0.8617549  -0.25561937 -2.79858911 -1.7715331 ]
 [-0.69987723  0.92746243 -0.17363568  0.00284592  0.68822271]
 [-0.87953634  0.28362732 -0.80536652 -1.72766949 -0.39089979]
 [ 0.57380586  0.33858905 -0.01183049  2.39236527  0.41291216]
 [ 0.97873601  2.23814334 -1.29408532 -1.03878821  1.74371223]]


In [26]:
#13. How to find common values between two arrays?
x = np.arange(3,8)
y = np.arange(6,9)
print(np.intersect1d(x,y))

[6 7]


In [28]:
#14. Create a random vector of size 10 and sort it
np.random.seed(123)
a = list(np.random.random(10))
a.sort()
print(a)

[0.2268514535642031, 0.28613933495037946, 0.3921175181941505, 0.42310646012446096, 0.48093190148436094, 0.5513147690828912, 0.6848297385848633, 0.6964691855978616, 0.7194689697855631, 0.9807641983846155]


In [33]:
#15 Create random vector of size 10 and replace the maximum value by 0
np.random.seed(123)
x = np.random.random(10)
x = list(x)
i = np.argmax(x)
x = x[:i]+[0]+x[i+1:]
x

[0.6964691855978616,
 0.28613933495037946,
 0.2268514535642031,
 0.5513147690828912,
 0.7194689697855631,
 0.42310646012446096,
 0,
 0.6848297385848633,
 0.48093190148436094,
 0.3921175181941505]

In [34]:
#16. Subtract the mean of each row of a matrix 
a = np.random.rand(3, 4)
print(a)
a.mean(axis=1, keepdims=True)

[[0.34317802 0.72904971 0.43857224 0.0596779 ]
 [0.39804426 0.73799541 0.18249173 0.17545176]
 [0.53155137 0.53182759 0.63440096 0.84943179]]


array([[0.39261947],
       [0.37349579],
       [0.63680293]])

In [35]:
#18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares

a = np.arange(15).reshape(5,3)
a
np.where(a < 4, a, a**2)

array([[  0,   1,   2],
       [  3,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])

In [36]:
#17. How to get the n largest values of an array (★★★)
a = np.arange(15).reshape(5,3)
a
np.where(a < 4, a, a**2)

array([[  0,   1,   2],
       [  3,  16,  25],
       [ 36,  49,  64],
       [ 81, 100, 121],
       [144, 169, 196]])